### PR TITLE
[opentelemetry-collector] Use tpl with configmap

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Updates the configmap helpers to run the configuration through `tpl`.  `.Values.config` now supports templating.  Affects daemonset, deployment, and statefulset configmaps.

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
Looks good to me

**Comment by dmitryax** [comment]
Actually I think there are might be corner cases when this is undesirable. We should document how to escape it or make it optional/configurable feature

**Review by Allex1 — APPROVED** [review]

**Comment by Allex1** [comment]
> Actually I think there are might be corner cases when this is undesirable. We should document how to escape it or make it optional/configurable feature

Can you pls provide some examples @dmitryax? We're using this internally in multiple charts.

**Comment by dmitryax** [comment]
For example when user want to use something with `{{ }}` in a value, for example:

```yaml
config:
  processors:
    attributes:
      actions:
        - key: email
           action: update
           value: "{{ REDACTED_EMAIL }}" 
```

I think this will fail. 

I believe at least we should document a way to escape such values

**Comment by TylerHelmuth** [comment]
@dmitryax @Allex1 we can handle that situation with this escape sequence.

```yaml
config:
  processors:
    attributes:
      actions:
        - key: email
          action: update
          value: '{{ "{{" }} REDACTED_EMAIL {{ "}}" }}'
```

The result it

```yaml
config:
  processors:
    attributes:
      actions:
        - key: email
          action: update
          value: '{{ REDACTED_EMAIL }}'
```

**Comment by Allex1** [comment]
> @dmitryax @Allex1 we can handle that situation with this escape sequence.
> 
> ```yaml
> config:
>   processors:
>     attributes:
>       actions:
>         - key: email
>           action: update
>           value: '{{ "{{" }} REDACTED_EMAIL {{ "}}" }}'
> ```
> 
> The result it
> 
> ```yaml
> config:
>   processors:
>     attributes:
>       actions:
>         - key: email
>           action: update
>           value: '{{ REDACTED_EMAIL }}'
> ```
@TylerHelmuth this also works and looks better
``` `{{ {{ REDACTED_EMAIL }} `}} ```

**Comment by dmitryax** [comment]
Yes, we just need to document this in values.yaml probably

**Review by dmitryax — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@Allex1 Thanks, I'll update accordingly.

**Pull request merged**
