### PR TITLE
Add Allex1 as an approver

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Proposal to add @Allex1 as an approver for opentelemetry-helm-charts.

Alex has been a driving force for the operator chart and helps review PRs across the repo.

- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/297
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/289
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/285
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/278
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/276
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/268
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/266
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/265
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/258
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/256
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/255
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/253
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/251
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/249
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/245
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/244
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/240
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/235

@Allex1 Let me know if I've got your information correct in the readme. Thanks again for all your help!

cc @open-telemetry/helm-approvers

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
Thank you for all the work here!

**Comment by dmitryax** [comment]
@TylerHelmuth updating maintainers list requires a version bump :)

**Comment by TylerHelmuth** [comment]
> @TylerHelmuth updating maintainers list requires a version bump :)

lol!

**Review by Allex1 — APPROVED** [review]
:)

**Comment by TylerHelmuth** [comment]
@Allex1 you'll get an invite to  https://github.com/orgs/open-telemetry/teams/helm-approvers  shortly.  Welcome aboard!

**Pull request merged**
