### PR TITLE
[operator] update lost testFramwork image override changes

### PR DESCRIPTION
**Pull request by JaredTan95**
Signed-off-by: Jared Tan <jian.tan@daocloud.io>

following: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/413/files

### CODE REVIEW

**Comment by Allex1** [comment]
@JaredTan95 pls run `make generate-examples` and commit changes

**Comment by JaredTan95** [comment]
`opentelemetry-demo` examples generated fails, I will check it soon.

**Review by Allex1 — APPROVED** [review]

**Comment by dmitryax** [comment]
@JaredTan95 please rebase

**Review by dmitryax — APPROVED** [review]

**Comment by JaredTan95** [comment]
> @JaredTan95 please rebase

done.

**Pull request merged**
