### PR TITLE
Define annotations in consistent way

### PR DESCRIPTION
**Pull request by yamagai**
Close https://github.com/open-telemetry/opentelemetry-helm-charts/issues/628.

Unified the way to define annotations as follows. (lables/extraLabels are already unified.)
```
annotations:
  {{- range $key, $value := .Values.annotations }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
```

### CODE REVIEW

**Comment by puckpuck** [comment]
Please bump the version on the demo chart as well

**Comment by yamagai** [comment]
Oops, I missed it. Done.

**Comment by dmitryax** [comment]
I agree that we need a consistent way, but why is this one considered a better way? If the list is empty, it'll render 

```yaml
annotations: null
```

Even if k8s can read it, it's not correct IMO

**Comment by Allex1** [comment]
@yamagai I think you should split this pr, one for each chart as it's hard to review.

**Comment by yamagai** [comment]
> why is this one considered a better way?

I understood that the problem with using "with statement" was that the root context in the block would become `.Values.annotations` as mentioned [here](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/627#discussion_r1097642493)

This is also described in helm document: [here](https://helm.sh/docs/chart_template_guide/variables/).

For example, we can use global context in setting annotations like below
```
# values.yaml
annotations:
  hoge: hoge
  fuga: "{{ tpl (.Release.Name) . }}"

# template
annotations:
  {{- range $key, $value := .Values.annotations }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}

# output
annotations:
  fuga: "release-name"
  hoge: "hoge"
```

But we cannot use global context in setting annotations like below
```
# values.yaml
annotations:
  hoge: hoge
  fuga: "{{ tpl (.Release.Name) . }}"

# template
{{- with .Values.annotations }}
annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}

# output
annotations:
  fuga: '{{ tpl (.Release.Name) . }}'
  hoge: "hoge"
```

how do you think? @Allex1 @dmitryax 

> it's not correct IMO

I feel you 🧐 
how about the following way? this is the only way I could think of that doesn't use "with statement"...
```
  {{ if .Values.annotations }}
  annotations:
    ....
  {{ end }}
```

**Comment by yamagai** [comment]
> I think you should split this pr, one for each chart as it's hard to review.

Okay.
Once an implementation policy has been decided, I will split this pr 🚀

**Comment by dmitryax** [comment]
Ok, I see the problem now. Wrapping it with the if statements sounds good to me

**Comment by yamagai** [comment]
split this PR like below. So, this PR will close.

https://github.com/open-telemetry/opentelemetry-helm-charts/pull/674
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/675
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/676

**Pull request closed without merging**
