### PR TITLE
[opentelemetry-collector] fixed the image version of busybox to latest in all examples

### PR DESCRIPTION
**Pull request by sherifkayad**
a forgotten minor minor change related to #651

### CODE REVIEW

**Comment by sherifkayad** [comment]
@povilasv I really don't have a big preference here. My motivation of fixing a version is basically that it's kinda a Kubernetes best practice to do.

If for some reason that is not applicable here, I am also fine with closing this PR. As you prefer.

**Comment by TylerHelmuth** [comment]
@sherifkayad I tend to agree with @povilasv.  Since this section is acting more like a comment/warning, I think using latest is fine.

**Comment by sherifkayad** [comment]
@TylerHelmuth @povilasv done as requested.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by sherifkayad** [comment]
@povilasv done!

**Comment by TylerHelmuth** [comment]
@sherifkayad I messed up and merged another collector chart PR before this one.  Please rebase.

**Comment by sherifkayad** [comment]
@TylerHelmuth all good. Rebased and adjusted the new version

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
