### PR TITLE
[opentelemetry-collector] add support for hostnetworking in deployment and statefulset mode

### PR DESCRIPTION
**Pull request by povilasv**
At the moment only daemonset supports `hostNetwork` option, so I'm fixing this :)

### CODE REVIEW

**Review by Allex1 — APPROVED** [review]
lgtm

**Review by dmitryax — COMMENTED** [review]
The change LGTM. But I'm curios, do you really have a use case where it's needed?

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Please rebase and update the version

**Comment by dmitryax** [comment]
Cool. Makes sense to merge it anyway just to for consistency

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
