### PR TITLE
[collector] Enable `retry_on_failure` for filelog receiver created by logsCollection preset

### PR DESCRIPTION
**Pull request by husnialhamdani**
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/822

Add `retry_on_failure` setting to filelog

### CODE REVIEW

**Comment by husnialhamdani** [comment]
@TylerHelmuth am I adding on a correct place?

**Comment by TylerHelmuth** [comment]
@husnialhamdani no, you'll want to make the changes here: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/21b8e825c72f038378795ebfda94d5b6139fe26e/charts/opentelemetry-collector/templates/_config.tpl#L190.  We only add the filelog receiver when the `presets.logsCollection` is enabled, so we should not modify the default config.

**Comment by husnialhamdani** [comment]
> @husnialhamdani no, you'll want to make the changes here:
> 
> https://github.com/open-telemetry/opentelemetry-helm-charts/blob/21b8e825c72f038378795ebfda94d5b6139fe26e/charts/opentelemetry-collector/templates/_config.tpl#L190
> 
> . We only add the filelog receiver when the `presets.logsCollection` is enabled, so we should not modify the default config in the values.yaml.

updating

**Comment by husnialhamdani** [comment]
> Please update chart version and generate examples

Will it minor or major version change?,
for generate example, i think we should add only under [this directory](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector/examples/daemonset-collector-logs), isn't it?

Is there any hack script or just render the Helm chart manually?

**Review by TylerHelmuth — COMMENTED** [review]
@husnialhamdani please regenerate the examples 1 more time as bumping the version affects the examples.

**Comment by husnialhamdani** [comment]
> @husnialhamdani please regenerate the examples 1 more time as bumping the version affects the examples.

done

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
