### PR TITLE
Remove unknown fields from CRD file

### PR DESCRIPTION
**Pull request by KqLLL**
Error while upgrading CRD resource.
```shell
 error validating data: [ValidationError(CustomResourceDefinition): unknown field "roleRef" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition, ValidationError(CustomResourceDefinition): unknown field "rules" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition, ValidationError(CustomResourceDefinition): unknown field "subjects" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition, ValidationError(CustomResourceDefinition): unknown field "webhooks" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition];

### CODE REVIEW

**Comment by dmitryax** [comment]
Hey @KqLLL. Is this PR still relevant? Please bump the chart version to avoid linter failures

**Comment by KqLLL** [comment]
Thx @dmitryax.  Bumped the chart version.

**Comment by awx-kqkq** [comment]
Same issue here.

Please review and merge this! Many thanks!

**Comment by dmitryax** [comment]
@KqLLL the main branch was failing, now it's fixed. Can you rebase please?

**Comment by KqLLL** [comment]
This issue has been fixed in the new version. PR closed.

**Pull request closed without merging**
