### PR TITLE
[opentelemetry-collector] Add statefulset mode

### LINKED ISSUE #177: Add ability to install collector as a StatefulSet
The opentelemetry-collector chart should have an option to be installed as a StatefulSet.  This will allow us to better support certain configurations, such as agents sending data via the loadbalancing exporter.

### PR DESCRIPTION
**Pull request by TylerHelmuth**
This PR adds a new mode to the collector chart: `statefulset`.  When `mode: statefulset` is used, the collector will be deployed as a statefulset.

I will bump the chart version once the PR is reviewed.

Closes #177

### CODE REVIEW

**Comment by dmitryax** [comment]
Looks like the issue in the description is incorrect

**Comment by dmitryax** [comment]
Please take a look at the failing linter

**Comment by TylerHelmuth** [comment]
> Please take a look at the failing linter

It's the chart version bump.  I was gonna hold off on the bump until the core changes can be reviewed, since the bump will trigger the examples to change and clutter up the files.

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by sherifkayad** [comment]
@TylerHelmuth Looks really good thanks for the heads up

**Comment by TylerHelmuth** [comment]
@sherifkayad No problem. If you use this feature and run into any issues let us know.

**Comment by sherifkayad** [comment]
Sure thing will do 😉

**Comment by sherifkayad** [comment]
@TylerHelmuth seems like the `volumeClaimTemplates` isn't taken into consideration for some reason .. My Yaml config is as follows:
```yaml
statefulset:
  # volumeClaimTemplates for a statefulset
  volumeClaimTemplates:
  - metadata:
      name: opentelemetry-collector-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  podManagementPolicy: "Parallel"
```

**Comment by sherifkayad** [comment]
On another notes, I am also getting this error:
`create Pod opentelemetry-collector-0 in StatefulSet opentelemetry-collector failed error: Pod "opentelemetry-collector-0" is invalid: spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: "kubernetes.io/hostname null": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')`

My affinity settings are as follows:
```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: opentelemetry-collector
        topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

**Comment by sherifkayad** [comment]
I opened #368 addressing both these issues.

**Pull request merged**
