### PR TITLE
Update Operator README.md

### PR DESCRIPTION
**Pull request by crossoverJie**
Supplementary delete command.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
@crossoverJie please bump the chart's patch version and then run `make generate-examples CHARTS=opentelemetry-operator`

**Comment by crossoverJie** [comment]
> @crossoverJie please bump the chart's patch version and then run `make generate-examples CHARTS=opentelemetry-operator`

Done.

**Review by TylerHelmuth — APPROVED** [review]

**Review by JaredTan95 — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@crossoverJie there is something wrong with your examples.  Please run `make generate-examples CHARTS=opentelemetry-operator`

**Comment by crossoverJie** [comment]
> @crossoverJie there is something wrong with your examples. Please run `make generate-examples CHARTS=opentelemetry-operator`

Done.

**Pull request merged**
