### PR TITLE
Allow for secure deployments by default.

### PR DESCRIPTION
**Pull request by LouisParkin**
When attempting to deploy the demo in a cluster that enforces `runAsRoot: false` fro all containers, the deployment had more failing pods than successful ones.

This change introduces the option to specify securityContext at a pod level through the pod spec, injecting values from the values.yaml file.

Example:
```yaml
default:
  podSecurityContext:
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
```
Now both containers and initContainers get the correct security context by default.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
Please update the comments in the `values.yaml` that detail possible allowed sections

**Comment by LouisParkin** [comment]
> Please update the comments in the `values.yaml` that detail possible allowed sections

Done :-)

**Review by puckpuck — APPROVED** [review]
Thanks for this

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Please run `make generate-examples`

**Comment by LouisParkin** [comment]
> make generate-examples

@dmitryax and then push again?

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
