### PR TITLE
docs: Remove S from extraVolumeMounts

### PR DESCRIPTION
**Pull request by vladohotnikov**
Remove S from extraVolumeMounts in [documentation](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/7a9309da0b47eae2853c010fd4ee8e45cb9999f3/charts/opentelemetry-collector/templates/NOTES.txt#L10)

### CODE REVIEW

**Review by TylerHelmuth — CHANGES_REQUESTED** [review]
`extraVolumeMounts` is the correct field name since it adds entries to the `volumeMounts` section.  Instead of changing this field name, can you fix the typo in the message in NOTES.txt?

**Comment by vladohotnikov** [comment]
> `extraVolumeMounts` is the correct field name since it adds entries to the `volumeMounts` section. Instead of changing this field name, can you fix the typo in the message in NOTES.txt?

Sure, done. Thank you for clarification.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by vladohotnikov** [comment]
Regenerate examples with new version [error](https://github.com/open-telemetry/opentelemetry-helm-charts/runs/6906914869?check_suite_focus=true).

**Comment by TylerHelmuth** [comment]
@dmitryax please review

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
