### PR TITLE
Update helm chart to account for changes to loadgenerator 

### PR DESCRIPTION
**Pull request by Mwad22**
Now that [this issue](https://github.com/open-telemetry/opentelemetry-demo/issues/320#issue-1343389309) in opentelemetry-demo repo has been resolved, the helm chart needs to be changed. Specifically, my PR maps the changes in this [merged PR](https://github.com/open-telemetry/opentelemetry-demo/pull/316) to do the following:

1. account for new environment variables in loadgenerator 
2. deploy load generator as a service (by adding `servicePort` field) so users can use `kubectl port-forward [service] [port]` and interact with the locust UI
3. Generates the specific command to expose Locust UI in NOTES.txt.

**NOTE: this can only be merged after new images are built/deployed as current images built the loadgenerator with different environment variables and a `--headless` tag that disables the locust UI** 

Re: Testing
I have tested the full functionality following helm chart changes on k8s by generating the template (using `helm template`) and replacing the image with my own docker image of locust.

### CODE REVIEW

**Comment by dmitryax** [comment]
@Mwad22 please sign the CLA

**Comment by Mwad22** [comment]
> @Mwad22 please sign the CLA

Just signed!

**Comment by TylerHelmuth** [comment]
@Mwad22 do you know how long it'll be till the new images our available?

**Comment by Mwad22** [comment]
> @Mwad22 do you know how long it'll be till the new images our available?

I believe once [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/285) lands.  @austinlparker @puckpuck   I believe this was mentioned in the otel-demo slack, but can one of you confirm? thanks!

**Comment by TylerHelmuth** [comment]
@Mwad22 still interested in this PR?

**Comment by Mwad22** [comment]
Yes, will update it tomorrow!

**Comment by TylerHelmuth** [comment]
@Mwad22 I think there are some other defects affecting the demo chart that are causing your build to fail.  I'll review this again when those are fixed in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/344

**Comment by TylerHelmuth** [comment]
@Mwad22 please bump the chart version

**Comment by Mwad22** [comment]
> @Mwad22 please bump the chart version

Just bumped it!

**Comment by TylerHelmuth** [comment]
@Mwad22 have you tested this branch with the new official demo images (0.3.4)?

**Review by Allex1 — APPROVED** [review]
lgtm

**Comment by Mwad22** [comment]
> @Mwad22 have you tested this branch with the new official demo images (0.3.4)?

I just tested it again, everything seems to work as expected- with the new Locust UI and everything else!

**Pull request merged**
