### PR TITLE
add ability to add extra config for kube-rbac-proxy

### LINKED ISSUE #500: Ability to config tls setting for kube-rbac-proxy
kube-rbac-proxy support below setting
--tls-cert-file                        
--tls-cipher-suites   
--tls-min-version
--tls-private-key-file
--tls-reload-interval 

It is better if we can configure it from helm value ?

### PR DESCRIPTION
**Pull request by kangsheng89**
fixed #500

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by kangsheng89** [comment]
@dmitryax can help for rerun the workflow?

**Review by Allex1 — APPROVED** [review]
after rebase and generate examples

**Comment by kangsheng89** [comment]
@TylerHelmuth i run in on my local, it is fine, seem like the workflow is breaking. I saw few actions has the similar issue.

**Comment by Allex1** [comment]
@kangsheng89 you need to bump the chart version and run `make generate-examples` from the root path of this repo(locally) and then commit the changes being generated.

**Comment by kangsheng89** [comment]
@Allex1 thx for your guid. Sorry a bit unfamiliar with the process..LOL

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
