### PR TITLE
[collector] feat: add 'relabelings' and 'metricRelabelings' configs to serviceMonitor

### PR DESCRIPTION
**Pull request by rl0nergan**
Adds the ability to add relabeling and metricRelabeling configs to the collector serviceMonitor created by the opentelemetry-collector helm chart. Resolves https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1240

### CODE REVIEW

**Review by TylerHelmuth — CHANGES_REQUESTED** [review]
I'd like to continue discussing in the issue before implementing the relableing solution. I believe the Collector already has a solution.

**Comment by rl0nergan** [comment]
@TylerHelmuth any updates on this?

**Review by TylerHelmuth — COMMENTED** [review]
Please fix conflicts

**Comment by TylerHelmuth** [comment]
you'll also need to run `make generate-examples CHARTS=opentelemetry-collector`

**Comment by rl0nergan** [comment]
done, updated examples have been pushed up

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
