### PR TITLE
[collector] Define annotations in consistent way

### PR DESCRIPTION
**Pull request by yamagai**
Close https://github.com/open-telemetry/opentelemetry-helm-charts/issues/628.

split PR(https://github.com/open-telemetry/opentelemetry-helm-charts/pull/671) for each charts. This PR is for opentelemetry-collector chart.

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
please bump the chart version again

**Review by Allex1 — APPROVED** [review]

**Comment by yamagai** [comment]
@dmitryax Done :)

**Comment by yamagai** [comment]
Sorry, I pushed by mistake, I'll fix it.

**Comment by yamagai** [comment]
rebase and adjust the chart version! 🚀

**Pull request merged**
