### PR TITLE
[opentelemetry-kube-stack] Enable operator install by default

### PR DESCRIPTION
**Pull request by TylerHelmuth**

### CODE REVIEW

**Comment by jaronoff97** [comment]
@TylerHelmuth looks like we need to give this a custom name:
```
Error: INSTALLATION FAILED: Service "opentelemetry-kube-stack-ybqc8oya3n-opentelemetry-operator-webhook" is invalid: metadata.name: Invalid value: "opentelemetry-kube-stack-ybqc8oya3n-opentelemetry-operator-webhook": must be no more than 63 characters

```

**Comment by TylerHelmuth** [comment]
We are also hitting a race condition in testing now that the operator is being installed.  This needs more investigation, so I am going to open an issue and disable ct install for now

**Comment by TylerHelmuth** [comment]
Created https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1300

**Comment by jaronoff97** [comment]
closed by #1305

**Pull request closed without merging**
