### PR TITLE
[operator] bump operator version to v0.104.0

### PR DESCRIPTION
**Pull request by frzifus**

### CODE REVIEW

**Review by jaronoff97 — COMMENTED** [review]
@frzifus you need to bump the chart version to 0.65.0

**Review by jaronoff97 — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@frzifus can you handle the conflicts

**Comment by frzifus** [comment]
Resolved @jaronoff97 @TylerHelmuth

**Review by jaronoff97 — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@frzifus one of the tests is failing and rerunning isn't working :(

**Comment by TylerHelmuth** [comment]
did something change in 0.104.0?

**Comment by frzifus** [comment]
Nothing I am aware about. The output off `    --- FAIL: chainsaw/smoke-pod-dns-config (365.29s)` does also not rly help.

**Comment by TylerHelmuth** [comment]
@frzifus does the test pass locally?

**Comment by jaronoff97** [comment]
this seems to be the issue (ran it locally)
```
⫸ k logs poddnsconfig-collector-6d9c74b776-xsh9q
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': unknown type: "logging" for id: "logging" (valid values: [nop otlp otlphttp file loadbalancing debug])
2024/08/01 15:25:52 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': unknown type: "logging" for id: "logging" (valid values: [nop otlp otlphttp file loadbalancing debug])
```

**Comment by jaronoff97** [comment]
this is because we're using the k8s distro which [no longer has the logging exporter](https://github.com/search?q=repo:open-telemetry/opentelemetry-collector-releases%20logging&type=code). @TylerHelmuth I can push a fix in the operator repo for the test there and we can ignore this test failure until the 106 release. @frzifus can you add this to the exclude regex [here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/.github/workflows/operator-test.yaml#L67C15-L67C103)?

**Review by jaronoff97 — APPROVED** [review]

**Comment by frzifus** [comment]
FTR: https://github.com/open-telemetry/opentelemetry-operator/pull/3192

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
