### PR TITLE
[demo] Remove FeatureFlagService and add flagd

### PR DESCRIPTION
**Pull request by julianocosta89**
The PR https://github.com/open-telemetry/opentelemetry-demo/pull/1388 removed FeatureFlag Service and replaced it with flagd.

This PR updates the charts to reflect the latest changes on the demo.
It also updates the dependencies charts.

### CODE REVIEW

**Comment by julianocosta89** [comment]
@puckpuck you mention in the `.env` file that `# must also update version field in /src/grafana/provisioning/datasources/opensearch.yml`, does that also apply for the Helm Chart?

I've updated opensearch, but I couldn't find where to update it on Grafana datasource.

**Comment by puckpuck** [comment]
Line 809 of the values file for the Helm chart. 

I'm on PTO using my phone so apologies for the short message.

**Comment by julianocosta89** [comment]
> Line 809 of the values file for the Helm chart.

Thank you!

**Comment by julianocosta89** [comment]
Hey @TylerHelmuth 👋🏽 

Do you happen to know what am I doing wrong here?
I'm trying to create the flagd configMap and attach it to the container, but I'm failing miserably 😭

**Comment by AlexPSplunk** [comment]
For me the flagd container just runs and exits as if no config has been specified.  Configmap appears to be mounted at /etc/flagd.  Below is the output I get when looking at the flagd container logs:

```
$ kubectl logs astroshop-edu-o11y-flagd-6f85c496b9-j2f5f

		 ______   __       ________   _______    ______
		/_____/\ /_/\     /_______/\ /______/\  /_____/\
		\::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \
		 \:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\ \ \ \
		  \:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \
		   \:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| |
		    \_\/     \_____\/ \__\/\__\/ \_____\/   \____/_/

Flagd is a simple command line tool for fetching and presenting feature flags to services. It is designed to conform to Open Feature schema for flag definitions.

Usage:
  flagd [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  start       Start flagd
  version     Print the version number of flagd

Flags:
      --config string   config file (default is $HOME/.agent.yaml)
  -x, --debug           verbose logging
  -h, --help            help for flagd

Use "flagd [command] --help" for more information about a command.```

**Comment by puckpuck** [comment]
@julianocosta89 I pushed a commit to your branch to get flagd working. There were a few small other issues, but the main one was having to specify the command arguments.

This did bring up an interesting point. Right now we have 2 environment variables, `FLAGD_HOST` and `FLAGD_PORT`. The demo uses both of these, but for everything else, we use a single `_ADDR` variant instead. I think we should update the demo to use this single variable instead.

**Comment by julianocosta89** [comment]
@puckpuck I actually started doing that, but glad doesn't support it.

https://flagd.dev/reference/specifications/in-process-providers/?h=environmen#explicit-declaration

I'm on the phone so the link may not be pointing to the right place, but check out the environment variables in this page.

**Comment by julianocosta89** [comment]
BTW, thanks for taking a look and fixing the PR

**Comment by julianocosta89** [comment]
Would we be able to get this merged?
We are getting a bunch of PRs in the demo that would require helm updates, but the flagd is not merged yet.

**Comment by puckpuck** [comment]
We need the demo to cut a release first, then we can target those images in this Helm chart to ensure all CI tests pass.

**Comment by julianocosta89** [comment]
@puckpuck this one should be good to go! 🥳

**Comment by puckpuck** [comment]
@julianocosta89 I updated NOTES.txt to remove references to the old feature flag UI, and replaced demo.flagd.json with the same from the demo repo to ensure they are the same.

Everything looks good!

**Review by puckpuck — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
