### PR TITLE
[operator] Bump operator to 0.94.0

### PR DESCRIPTION
**Pull request by TylerHelmuth**

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@open-telemetry/helm-approvers @open-telemetry/operator-approvers I wont have time to look at this for the next 2 weeks.  I believe the issue is only about setting up the tests properly, not the operator or the chart.

Honestly maybe we dont even need to run these tests? We don't do the same for the other charts.

**Comment by Allex1** [comment]
I'll take a look

**Comment by swiatekm-sumo** [comment]
I can take care of this as well, I've done so in the past and I'm familiar with operator E2E tests.

**Comment by Allex1** [comment]
@swiatekm-sumo it's all yours. Thanks

**Pull request closed without merging**
