### PR TITLE
Add ability to configure replicas for services

### PR DESCRIPTION
**Pull request by martinjt**
This PR adds 2 new settings to the `values.yaml`

- `default.replicas`
  This will configure how many replicas of each of the services should be create
- `components.<service>.replicaOverride`
  This will override the specific service's replicas from the default.

In the supplied `values.yaml` the `default.replicas` value is set to 1 so that it doesn't change for existing users. In addition there are specific services that I didn't think should be automatically scaled based on this setting, for these I've added a `replicasOverride` to their section to keep it at 1, users can obviously override these as they see fit. These are:

- Redis
- Postgres
- Kafka
- Load generator

I'm sure I need to update some change logs, but I'm not sure where, so any guidance would be appreciated.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
@martinjt looks great.  Please update the README with the new values.  Also, bump the chart's minor version and run `make generate-examples CHARTS=opentelmetry-demo`

**Comment by martinjt** [comment]
Thanks @TylerHelmuth are there any other stateful services that I missed in the replicasOverride?

**Comment by TylerHelmuth** [comment]
I'd like @puckpuck opinion, buy maybe `featureflagService` and `frontendProxy`.

**Comment by martinjt** [comment]
The Feature Flag service has a postgres database, so I figured that was ok, and I'd assumed the proxy wasn't stateful.

**Comment by martinjt** [comment]
The idea is to scale up all the services at once, and make that easier for the scenario of just "we want more load". which makes it easier than adding an entry for each of them. Also when/if new components are added, they'll immediately get the replicas.

**Review by puckpuck — APPROVED** [review]

**Comment by martinjt** [comment]
Sorry, yes, this was in relation to the question about example charts
changing on every release. Want me to PR the removal?

**Comment by martinjt** [comment]
No idea what's going on with that failure, it looks fine, I ran the generate-examples and committed them. Any ideas @puckpuck ?

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@martinjt looks like you've had a bad merge maybe? Please undo the changes to `./charts/opentelemetry-collector` and `./charts/opentelemetry-operator`. When re-rendering the demo examples use `make generate-examples CHARTS=opentelemetry-demo` so that only the demo examples are rendered.

**Pull request closed without merging**
