### PR TITLE
Remove move statement for run id

### LINKED ISSUE #204: Default filelog receiver config causes failure
When running with the default `filelog` receiver config, the following error is thrown when attempting to process log entries:

```
Failed to process entry	{"kind": "receiver", "name": "filelog", "operator_id": "move5", "operator_type": "move", "error": "move: field does not exist", ...
```

That error corresponds to this operator:
```
- from: attributes.run_id
  to: attributes["run_id"]
  type: move
```

Can this be removed?

### PR DESCRIPTION
**Pull request by lamebear**
Fixes #204

This PR removes a move command for the `run_id` attribute from the default `filelog` receiver config.

### CODE REVIEW

**Comment by dmitryax** [comment]
`run_id` attribute shouldn't be used.

Can you please solve https://github.com/open-telemetry/opentelemetry-helm-charts/issues/207 in this PR?

**Comment by dmitryax** [comment]
@lamebear please bump the chart version. We've got another PR merged

**Comment by dmitryax** [comment]
Also run `make generate-examples`

**Comment by dmitryax** [comment]
Please rebase

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
