### PR TITLE
feat(opentelemetry-collector): use Kubernetes recommended label for c…

### PR DESCRIPTION
**Pull request by nlamirault**
Use Kubernetes commended labels for `component` label.

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
I agree this is a breaking change.  We can add a new label but should leave the existing one for now.

**Comment by TylerHelmuth** [comment]
@nlamirault please bump the patch version of the chart and run `make generate-examples CHARTS=opentelemetry-collector`

**Review by jaronoff97 — APPROVED** [review]

**Comment by jaronoff97** [comment]
(once this is updated with the latest and examples are generated, should be good)

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@z0rc thanks, I'll submit a pr to fix this.

**Pull request merged**
