### PR TITLE
Updated default collector version to 0.49.0

### PR DESCRIPTION
**Pull request by TylerHelmuth**
This PR updates the default collector image version to 0.49.0. Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.

Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/168

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
[I think there was an issue with the 0.49.0 release.  ](https://github.com/open-telemetry/opentelemetry-collector-releases/releases).

**Comment by TylerHelmuth** [comment]
This PR should not be completed until #170 is fixed.

**Comment by dmitryax** [comment]
The release is delayed due to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9278

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Thanks @TylerHelmuth!

**Pull request merged**
