### PR TITLE
[operator] Add operator labels to crds

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Fixes an issue where the standard labels were not being added tot he templated CRDs.

### CODE REVIEW

**Review by jaronoff97 — APPROVED** [review]

**Comment by swiatekm-sumo** [comment]
Why is this necessary? We don't have these in the operator release bundle.

**Comment by TylerHelmuth** [comment]
@swiatekm-sumo I am 99% sure that if these labels aren't added then the installed CRDs won't be upgradable bc they wont have the `managed-by` [label and others](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/4845736e68736dd11122c2ed75f6213e9324b260/charts/opentelemetry-operator/templates/_helpers.tpl#L36-L45).

**Comment by TylerHelmuth** [comment]
Also someone please give me the right sed link to add to the makefile lol

**Comment by swiatekm-sumo** [comment]
> Also someone please give me the right sed link to add to the makefile lol

You mean on MacOS? Pretty sure installing gsed via brew works.

**Comment by swiatekm-sumo** [comment]
> @swiatekm-sumo I am 99% sure that if these labels aren't added then the installed CRDs won't be upgradable bc they wont have the `managed-by` [label and others](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/4845736e68736dd11122c2ed75f6213e9324b260/charts/opentelemetry-operator/templates/_helpers.tpl#L36-L45).

I remember testing this and it worked. Helm should add any labels it needs for release tracking on its own. I can re-test if you want.

**Comment by TylerHelmuth** [comment]
@swiatekm-sumo ya that would be good, my local testing showed otherwise.

**Comment by TylerHelmuth** [comment]
so it looks like we get 

```
Labels:       app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=opentelemetry-operator
Annotations:  controller-gen.kubebuilder.io/version: v0.14.0
              meta.helm.sh/release-name: testing
              meta.helm.sh/release-namespace: default
```

Which means we are missing `app.kubernetes.io/instance: {{ .Release.Name }}` but it an uninstall of the chart does remove the CRDs, so I was wrong.

**Pull request closed without merging**
