### PR TITLE
[opentelemetry-collector] Add ability to template initcontainers.

### PR DESCRIPTION
**Pull request by ancostas**
I have a use case where I need to interpolate global values into my initcontainer, so I've added the ability to template it. I think this is backwards compatible.

### CODE REVIEW

**Review by Allex1 — APPROVED** [review]
lgtm

**Review by puckpuck — APPROVED** [review]

**Comment by puckpuck** [comment]
@ancostas you'll need to update and generate-examples, then we can merge this.

**Comment by ancostas** [comment]
@puckpuck Done!

**Review by TylerHelmuth — COMMENTED** [review]
@ancostas to keep the number of examples to a minimum, can you merge your new lifecycle-hooks-with-globals example with the existing lifecycle-hookes example?

**Comment by ancostas** [comment]
@TylerHelmuth sure thing! I've also ignored IntelliJ IDE config in case any future contributors use that.

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
