### PR TITLE
update otel-collector to 0.19.0

### PR DESCRIPTION
**Pull request by naseemkullah**
also remove removed queued_retry

Signed-off-by: naseemkullah <naseem@transit.app>

### CODE REVIEW

**Comment by naseemkullah** [comment]
solves #19

**Review by tigrannajaryan — APPROVED** [review]
LGTM

**Comment by tigrannajaryan** [comment]
The lint check is stuck. May require to close and reopen the PR.

**Comment by naseemkullah** [comment]
I've updated the gh workflows as per what's new in https://github.com/helm/charts-repo-actions-demo (which they were based off originally). While unsure about what made it fail before, the check is passing now.

**Comment by tigrannajaryan** [comment]
@naseemkullah thank you.

**Comment by tigrannajaryan** [comment]
@naseemkullah the main branch build failed: https://github.com/open-telemetry/opentelemetry-helm-charts/runs/1792366706?check_suite_focus=true

Can you please revert this PR and check why the build fails?

**Comment by naseemkullah** [comment]
Sure!  I may attempt a fix forward if it is straightforward enough.

**Comment by naseemkullah** [comment]
this should do it @tigrannajaryan : https://github.com/open-telemetry/opentelemetry-helm-charts/pull/30

**Pull request merged**
