### PR TITLE
feat: Provide integration with Artifact Hub

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide integration with Artifact Hub so that Helm charts are discoverable there.

I have already created and configured an organization on Artifact Hub and configured it so that it will be [a verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher).

Once things are merged, you can apply to [claim official status](https://artifacthub.io/docs/topics/repositories/#official-status).

Outcome: https://artifacthub.io/packages/search?repo=opentelemetry-helm&sort=relevance&page=1

Relates to https://github.com/open-telemetry/opentelemetry-helm-charts/issues/108

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Moving follow-up action items to issue instead of PR

**Review by TylerHelmuth — APPROVED** [review]
Exciting stuff!

**Review by dmitryax — APPROVED** [review]
Thanks @tomkerkhove!

**Comment by tomkerkhove** [comment]
My pleasure, happy to help people use OpenTelemetry more!

**Pull request merged**
