### PR TITLE
Update Otel Operator to v0.41.0 release

### PR DESCRIPTION
**Pull request by VineethReddy02**
**Note**: A new CRD has been introduced in otel operator to support auto-instrumentation with otel operator deployments. 

Also, I'm one of the maintainers of Otel-Operator and an active user of the otel-operator helm chart. I would love to collaborate in the active development of these helm charts.

### CODE REVIEW

**Comment by dmitryax** [comment]
Hey @VineethReddy02 , thanks for your help. Can you please take a look into failing tests?

**Comment by VineethReddy02** [comment]
@dmitryax Can you helping me in fixing the CI, Everything looks good but the CI fails :/

**Comment by dmitryax** [comment]
@VineethReddy02 the failing tests are brought from the operator. I'm not familiar with them. Can you take a look why are they failing as an operator maintainer?

**Comment by VineethReddy02** [comment]
@dmitryax are there any docs on bumping helm charts? Just to confirm I'm copy pasting the new CRD spec from https://github.com/open-telemetry/opentelemetry-operator/blob/v0.41.0/bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml

Is this the right way of bumping CRDs?

**Comment by VineethReddy02** [comment]
@dmitryax Now the PR is ready for review :)

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
@VineethReddy02 thanks for fixing it!

**Pull request merged**
