### PR TITLE
OpenTelemetry operator 0.106.0

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by pavolloffay** [comment]
Shall we close or merge first https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1297  ?

**Comment by jaronoff97** [comment]
lets merge the 105 release first and then we can do this one

**Comment by TylerHelmuth** [comment]
@pavolloffay needs a chart minor version bump and the regenerate the examples

**Comment by pavolloffay** [comment]
@TylerHelmuth fixed, let me know if it is good now

**Review by jaronoff97 — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
