### PR TITLE
Add more configuration examples

### PR DESCRIPTION
**Pull request by dmitryax**
+ fix a zipkin port in examples

Issue: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/14

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]

**Comment by naseemkullah** [comment]
lgtm @dmitryax but one thing I still don't fully understand, why is it in the values.yaml file exporter is singular? Could we not instead have it be `exporters` and take a list of exporters?

On that note, perhaps having the `telemetry` value is a leaky abstraction? Can we just put some uncommented logging exporters  in `configOverride` ?

**Comment by dmitryax** [comment]
@naseemkullah I was thinking that the `telemetry` abstraction can cover most of the cases. 

It also provide an easy way to disable telemetry like 
```
telemetry:
  metrics:
    enabled: false
```

But it must be possible to do with
```
configOverride:
  service:
    pipelines:
      metrics: null
```
I'd need to verify it ^

So you may be right , it looks like unnecessary abstraction. We can remove it in `0.2.0` release. It's still early days of the chart.

**Comment by naseemkullah** [comment]
Sounds good @dmitryax, thanks!

**Comment by naseemkullah** [comment]
FWIW I'd hold off on these README example and remove the abstraction, if possible, and always encourage use of configOverride, i.e. I'd add examples along with `0.2.0`

**Comment by tigrannajaryan** [comment]
@naseemkullah Can I merge this or there are still concerns?

**Comment by naseemkullah** [comment]
We may want to go straight with `0.2.0` and only use `configOverride` and rid the chart of the potentially unnecessary abstraction value `telemetry`... @dmitryax does that make sense? I can open a PR for that if so.

**Comment by dmitryax** [comment]
@naseemkullah I agree, that makes sense. I'm OOO these days. please feel free to open the PR if you have a chance. otherwise I can do it probably next week

**Review by naseemkullah — CHANGES_REQUESTED** [review]
Will work on a `0.2.0` release, at which point the examples can be adapted to use the `configOverride` value exclusively

**Pull request closed without merging**
