### PR TITLE
[BUMP] - operator 0.73/collector 0.74

### PR DESCRIPTION
**Pull request by Allex1**
Should be merged after https://github.com/open-telemetry/opentelemetry-helm-charts/pull/678

### CODE REVIEW

**Comment by dmitryax** [comment]
@Allex1, the operator tests are failing

**Comment by Allex1** [comment]
> @Allex1, the operator tests are failing

I saw, I'll take a look on Monday. It's not obvious to me what's the issue.

**Comment by TylerHelmuth** [comment]
@Allex1 reviewing some of the changes made to the operator e2e director may help: https://github.com/open-telemetry/opentelemetry-operator/commits/main/tests/e2e.  It looks like there has been some HPA work recently

**Comment by Allex1** [comment]
> @Allex1 reviewing some of the changes made to the operator e2e director may help: https://github.com/open-telemetry/opentelemetry-operator/commits/main/tests/e2e. It looks like there has been some HPA work recently

saw that and opened https://github.com/open-telemetry/opentelemetry-operator/issues/1574 . Still not obvious, I'll attempt to run tests locally when I get a chance.

**Comment by TylerHelmuth** [comment]
@Allex1 opened https://github.com/open-telemetry/opentelemetry-operator/pull/1582 to improve the stability of the autoscale test.  If it gets merged, we'll be blocked on this PR until the commit is in an official release.

**Comment by Allex1** [comment]
Thanks @TylerHelmuth Seems to be working after your last pr by cloning main branch.

**Comment by TylerHelmuth** [comment]
@Allex1 we're ready for this again if we jump to 0.73.0

**Comment by Allex1** [comment]
@TylerHelmuth Thanks for the heads up. Done

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
