### PR TITLE
updates OTEL operator version to latest 0.58.0

### LINKED ISSUE #341: Update OTEL Operator version to latest (v0.58.0)
Support for .Net auto-instrumentation has been added in OTEL Operator release v0.57.2 and it has introduced the changes in the instrumentation CRD. 

I would like to raise a PR to make the helm chart of OTEL Operator to point to latest version of OTEL  Operator (v0.58.0).

### PR DESCRIPTION
**Pull request by avadhut123pisal**
Closes #341

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@avadhut123pisal looks like some new dotnet e2e tests are failing.  This chart runs the operator's e2e tests, so it is possible that when the e2e tests change in the operator we also need to make changes.  Can you investigate the failing test?

**Comment by avadhut123pisal** [comment]
> @avadhut123pisal looks like some new dotnet e2e tests are failing. This chart runs the operator's e2e tests, so it is possible that when the e2e tests change in the operator we also need to make changes. Can you investigate the failing test?

Yes. i will check.

**Comment by avadhut123pisal** [comment]
@TylerHelmuth  The test cases are failing, because it is not able to pull the docker image for the .Net auto-instrumentation.
We missed to set the default version of the .Net auto-instrumentation image in the image publish workflow of Operator, because of which it is using the 0.0.0 as a tag while pulling the image. I have raised a [PR](https://github.com/open-telemetry/opentelemetry-operator/pull/1060) fixing the same.

**Comment by VineethReddy02** [comment]
@avadhut123pisal The PR on the operator end is merged. Can you re-run the CI here?

**Comment by TylerHelmuth** [comment]
@VineethReddy02 Do we need new images to pickup the changes?

**Comment by avadhut123pisal** [comment]
> 

This issue is with the released image of Operator v0.58.0, so the test cases will not pass with the current image. I think, we need to wait for new release of the Operator. So, should we skip this version bump up in Operator helm chart for v0.58.0 and wait for next release ?

**Comment by TylerHelmuth** [comment]
@avadhut123pisal Yes if we need 0.59.0 images we'll skip 0.58.0. If that's the case, you can close this PR.

**Comment by avadhut123pisal** [comment]
Closing this PR because of the above mentioned reason.

**Pull request closed without merging**
