### PR TITLE
[demo] use Jaeger sub-chart

### PR DESCRIPTION
**Pull request by puckpuck**
Fixes: #515 

Moves to using a Jaeger sub-chart instead of templated within this chart itself.

This does introduce a potential breaking change, where the Jaeger parameters are moving to a top-level `jaeger.` section instead. Even though this is a breaking change, the chart is early enough, and the current section isn't likely to of been modified by existing deployments. 

A readme is also added to the chart to document the upgrade process and all parameters in the chart itself. 

Closing this would render #516 no longer required.

### CODE REVIEW

**Comment by puckpuck** [comment]
This one is ready for review now

**Review by julianocosta89 — APPROVED** [review]
Not an approver here, but it LGTM 🚀

**Comment by puckpuck** [comment]
I think we can certainly entertain using helm-docs to generate Docs instead.  For the demo chart in particular, because we have a section that repeats for each service component, it would take time to create the proper go template for the output docs and would prefer to defer that effort to another PR.

**Comment by TylerHelmuth** [comment]
That's true. I don't think it should block this PR, but something to think about.

**Comment by TylerHelmuth** [comment]
@dmitryax please review.

**Review by dmitryax — APPROVED** [review]
LGTM. Thanks for adding this!

**Pull request merged**
