### PR TITLE
Set topologySpreadConstraints type to array

### PR DESCRIPTION
**Pull request by gjacquet**
Set type to array in order to match type from Kubernetes API specs: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topologyspreadconstraints-field

Addresses #746

### CODE REVIEW

**Comment by gjacquet** [comment]
@Allex1 done!

**Review by TylerHelmuth — COMMENTED** [review]
@gjacquet can you provide a render of the new values.yaml in action?  I want to make sure the deployment template doesn't need changed.

**Comment by gjacquet** [comment]
In my case it gave something like this:
```yaml
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: opentelemetry-collector
        app.kubernetes.io/name: opentelemetry-collector
        component: standalone-collector
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: opentelemetry-collector
        app.kubernetes.io/name: opentelemetry-collector
        component: standalone-collector
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
```

**Comment by gjacquet** [comment]
I would not expect any change to be required as `toYaml` is used to render this value and it works on all sort of types, including lists and objects.
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_pod.tpl#L191

**Pull request merged**
