### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jdiegosierra**

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
Hello, thank your for these changes.  Please sign the CLA so we can proceed.

**Comment by JaredTan95** [comment]
I'm not sure if this kind of change would require bump up to the chart version? cc @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@JaredTan95 any change inside a chart folder require a version change.

**Comment by JaredTan95** [comment]
@jdiegosierra  pls following `Contributing.md` guide to polish this PR, in general, you need to bump up operator chart version and `CHARTS=opentelemetry-operator make generate-examples`  .

**Review by jaronoff97 — APPROVED** [review]

**Comment by JaredTan95** [comment]
@jdiegosierra any update?

**Review by jaronoff97 — APPROVED** [review]

**Comment by jdiegosierra** [comment]
@JaredTan95 Thank you for the info and sorry, I'll have a look today.

**Comment by jdiegosierra** [comment]
@TylerHelmuth done :)

**Review by TylerHelmuth — APPROVED** [review]

**Comment by jdiegosierra** [comment]
@TylerHelmuth any idea of why those test are failing? Is happening the same in my other PR https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1170

**Comment by TylerHelmuth** [comment]
Likely a flaky test

**Review by codeboten — APPROVED** [review]

**Pull request merged**
