### PR TITLE
[CHORE] adding ebpf collector

### PR DESCRIPTION
**Pull request by nicolastakashi**
As proposed on this https://github.com/open-telemetry/opentelemetry-ebpf/issues/186, I'm adding the eBPF collector as part of the collector helm chart.

### CODE REVIEW

**Comment by nicolastakashi** [comment]
cc @atoulme

**Comment by atoulme** [comment]
Nice! Thanks for this work.

**Comment by atoulme** [comment]
@nicolastakashi what would you think of making this a new top level chart? @TylerHelmuth is there a process to add a new chart?

**Comment by TylerHelmuth** [comment]
@atoulme new charts should be proposed via an Issue.

**Comment by TylerHelmuth** [comment]
@nicolastakashi I do not have the context necessary to review this PR.  Can you create an issue (or can we move the issue linked to this PR) to discuss what problem this PR solves?

**Comment by dmitryax** [comment]
I suggest making it another helm chart. Later, if we want it to be installable along with the collector, it can be set as a subchart. Or, just provide instructions on how to install it with the collector

**Comment by nicolastakashi** [comment]
Going to open another PR, cause I was struggling with conflicts

**Pull request closed without merging**
