### PR TITLE
Add new helm command to README.md, fix typos

### PR DESCRIPTION
**Pull request by MA3CIN**
+ Add link to logging exporter

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
@MA3CIN thanks for adding this.  Please bump the patch version of the chart and then run `make generate-examples CHARTS=opentelemetry-operator`

**Comment by MA3CIN** [comment]
@TylerHelmuth @povilasv I just bumped the minor version of the operator chart, should be good to go

**Review by TylerHelmuth — COMMENTED** [review]
@MA3CIN I hate to be annoying, but please bump the patch version instead.  The version should be `0.34.1` since we aren't adding any new features to the chart.

**Comment by MA3CIN** [comment]
@TylerHelmuth  You're right, no problem at all - I reverted the commit and bumped the version to 0.34.1. Should be good to go, next contributions will go smoother

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
