### PR TITLE
Add ability to create target allocator from helm chart

### LINKED ISSUE #334: [opentelemetry-collector] Make target allocator deployable via opentelemetry-collector helm chart
As suggested by @jaronoff97 via Slack here's a feature request to make the target allocator deployable via the collector helm chart.

My goal would be to have collector metric `scrape_configs` generated from `ServiceMonitor` CRDs.

### PR DESCRIPTION
**Pull request by jaronoff97**
Closes #334

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@jaronoff97 still interested in this? Haven't reviewed yet bc it's marked as draft.

**Comment by jaronoff97** [comment]
Yep, still interested. Have been working mainly on [this](https://github.com/open-telemetry/opentelemetry-operator/pull/1068) which has taken up a lot of my time

**Comment by M4C4R** [comment]
Is this still being introduced?

**Comment by jaronoff97** [comment]
@M4C4R this has gone stale as my focus has been working on target allocator stability and I haven't been able to prioritize this work. If you wish to use the target allocator still, you can use the operator for now, or manually configure the target allocator to run.

**Pull request closed without merging**
