### PR TITLE
Added environment variable and increased memory limit

### PR DESCRIPTION
**Pull request by jordibisbal8**
In this PR, we aim to add the environment variable `LOCUST_BROWSER_TRAFFIC_ENABLED` and increase the memory limit for the load generation. The main reason is to be able to run playwright in locust and generate web browser traffic. For more information, please have a look at the [corresponding PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1266)

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@jordibisbal8 I believe this would be better handled by setting those values in your values.yaml

**Comment by jordibisbal8** [comment]
> @jordibisbal8 I believe this would be better handled by setting those values in your values.yaml

If this is part of the docker-compose and Kubernetes configuration ([PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1266)), should this not be part of the charts configuration as well? :)

**Comment by TylerHelmuth** [comment]
@jordibisbal8 thanks for the new PR link, thats helpful.  I agree that if they changed it in the demo repo we should change it here.  Please bump the chart version and then run `make generate-examples CHARTS=opentelemetry-demo`.

**Comment by jordibisbal8** [comment]
> @jordibisbal8 thanks for the new PR link, thats helpful. I agree that if they changed it in the demo repo we should change it here. Please bump the chart version and then run `make generate-examples CHARTS=opentelemetry-demo`.

Done! https://github.com/open-telemetry/opentelemetry-helm-charts/pull/959/commits/622dfc83a15848971a0ad81ce4bd23862bf6f7d0
I have also run the generate-examples makefile but I do not see any changes :)

**Comment by jordibisbal8** [comment]
> > > @jordibisbal8 thanks for the new PR link, thats helpful. I agree that if they changed it in the demo repo we should change it here. Please bump the chart version and then run `make generate-examples CHARTS=opentelemetry-demo`.
> > 
> > 
> > Done! [622dfc8](https://github.com/open-telemetry/opentelemetry-helm-charts/commit/622dfc83a15848971a0ad81ce4bd23862bf6f7d0) I have also run the generate-examples makefile but I do not see any changes :)
> 
> It should generate the new examples, as you changed the chart version. Maybe you executed `make generate-examples CHARTS=opentelemetry-demo` before bumping the Chart.yaml?
> 
> Can you try `make generate-examples CHARTS=opentelemetry-demo` again?

Thanks for raising this, I was missing some helm dependencies :) 
It should have worked now -> https://github.com/open-telemetry/opentelemetry-helm-charts/pull/959#issuecomment-1831427232

**Review by TylerHelmuth — COMMENTED** [review]
These changes correspond to a change in the demo that hasn't been released yet. I believe we'll want to wait to accept them until demo 1.7.0 is out.  @puckpuck @austinlparker can you confirm?

**Comment by puckpuck** [comment]
Let's hold this off until we have a 1.7 release for the demo.

**Comment by puckpuck** [comment]
We opted not to move forward with the Playwright integration for the demo 1.7 release, so will close this PR.

**Pull request closed without merging**
