### PR TITLE
[operator] bump to 0.86.0

### PR DESCRIPTION
**Pull request by macmiranda**
Needed for correct operation after installing manager `v0.86.0` due to
https://github.com/open-telemetry/opentelemetry-operator/pull/2141/

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@macmiranda we haven't bumped the operator-chart yet to require these new cluster roles.  Would you like to do the bump?  https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/CONTRIBUTING.md#bumping-default-operator-version

**Review by TylerHelmuth — APPROVED** [review]

**Comment by macmiranda** [comment]
Hey @Allex1 @TylerHelmuth any idea when this will be merged?

**Comment by Allex1** [comment]
> Hey @Allex1 @TylerHelmuth any idea when this will be merged?

Hopefully today on the US timezone

**Comment by MrAlias** [comment]
@dependabot rebase

**Pull request merged**
