### PR TITLE
Promote JaredTan95 to Approver

### PR DESCRIPTION
**Pull request by TylerHelmuth**
@JaredTan95 has been a big help with all the helm charts recently, reviewing PRs and contributing improvements.

@JaredTan95 if there is any additional info you'd like added to your entry or a specific chart you'd like added to in CODEOWNERS please let me know.

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
👍

**Comment by dmitryax** [comment]
@JaredTan95 please approve :)

**Review by JaredTan95 — APPROVED** [review]
Thanks for the recognition, I approve

**Review by Allex1 — APPROVED** [review]
:tada:

**Pull request merged**
