### PR TITLE
Simplify error scenario logic

### PR DESCRIPTION
**Pull request by beeme1mr**
Relates to https://github.com/open-telemetry/opentelemetry-demo/pull/1657

### CODE REVIEW

**Review by puckpuck — APPROVED** [review]

**Review by TylerHelmuth — COMMENTED** [review]
@beeme1mr please bump the chart version and run `make generate-examples CHARTS=opentelemetry-demo`

**Comment by beeme1mr** [comment]
Hey @TylerHelmuth, the make command failed for some reason. I'll try and troubleshoot it when I have time. Is there any chance you could run it for me to get this PR unblocked? Thanks!

**Comment by jaronoff97** [comment]
@beeme1mr I did just that here https://github.com/beeme1mr/opentelemetry-helm-charts/pull/1 you can merge that in and your branch will have the update :)

**Comment by beeme1mr** [comment]
Thanks @jaronoff97!

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
