### PR TITLE
Allow to split the image registry and the repository

### PR DESCRIPTION
**Pull request by aacevedoosorio**
The current helm chart allows to set a `global.imageRegistry` in combination with the repository configured. But it would be nice as well to split the repository into the default registry for charts that use the open-telemetry chart as a subchart and have a default predefined repository.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
Please run `make generate-examples CHARTS=opentelemetry-collector`

**Review by TylerHelmuth — COMMENTED** [review]
We don't need a new example, but can you share the output of the image string being set properly when using the new field and the global field?

**Comment by aacevedoosorio** [comment]
> We don't need a new example, but can you share the output of the image string being set properly when using the new field and the global field?

I ended up creating the examples. I think they are valuable

**Review by TylerHelmuth — COMMENTED** [review]
@aacevedoosorio the new examples give me confidence that this process works, but I don't want to merge this PR with them.  Using these options in the values.yaml is straight forward for an end-user even if the logic to build the string is kinda complex.

**Comment by aacevedoosorio** [comment]
> @aacevedoosorio the new examples give me confidence that this process works, but I don't want to merge this PR with them. Using these options in the values.yaml is straight forward for an end-user even if the logic to build the string is kinda complex.

I get your point. Let me revert those examples.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@aacevedoosorio needs a rebase and then we'll be good.

**Pull request closed without merging**
