### PR TITLE
Add ability to mount extra ConfigMaps to OTel collector pods

### PR DESCRIPTION
**Pull request by kaz-zahed**
This PR would add the ability to mount extra ConfigMaps by setting the `extraConfigMapMounts` value.

Values set example:

```yaml
standaloneCollector:
  enabled: true
  
  configOverride:
    receivers:
      jaeger:
        protocols:
          grpc:
        remote_sampling:
          strategy_file: "/conf/jaeger/strategies.json"

extraConfigMapMounts:
- name: jaeger-sampling-strategies
  configMap: jaeger-sampling-strategies
  mountPath: /conf/jaeger
  readOnly: true
```

Extra ConfigMap example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-sampling-strategies
data:
  strategies.json: |-
    {
      "default_strategy":
        {
          "type": "probabilistic",
          "param": 1
        }
    }
```

### CODE REVIEW

**Comment by dmitryax** [comment]
@kaz-zahed thanks for the contribution. please bump the chart version

**Comment by kaz-zahed** [comment]
@dmitryax I bumped the version from 0.5.4 to 0.5.6 because PR #46 already bumped version to 0.5.5.

**Comment by dmitryax** [comment]
@kaz-zahed please rebase your change

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@kaz-zahed thank you

**Pull request merged**
