### PR TITLE
feat(collector): allow deployment of ingress for standaloneCollector

### LINKED ISSUE #76: Add optional ingress for otel collector
It might be useful for exposing the collector for SPA apps (react) and perhaps adding another way of redirecting requests to a oauth proxy.

### PR DESCRIPTION
**Pull request by secustor**
Allows to deploy an ingress object for the collector service

Fixes #76

### CODE REVIEW

**Comment by secustor** [comment]
Can somebody restart the pipeline. It seems like the scheduling has failed

**Comment by secustor** [comment]
@dmitryax

**Comment by Mahpara93** [comment]
Really interested in this feature.

**Comment by dmitryax** [comment]
Sorry for the delay. I need to look deeply into this use case. Will review later this week

**Comment by secustor** [comment]
This is one of the use cases https://docs.google.com/presentation/d/1jPDH8Csv-Qle7Z-P7rFJgjOsBpgKeehPhjFPqTRET1Y/mobilepresent#slide=id.gf87b11edd5_0_182

A static website is instrumented with OpenTelemetry  and sends telemetry to an OTLP endpoint.

**Review by dmitryax — APPROVED** [review]
LGTM

**Pull request merged**
