### PR TITLE
Adding namespace scope to webhook config

### LINKED ISSUE #939: [opentelemetry-operator] Webhook configuration rules are missing the scope field
Hello!

We're running a few GKE clusters and recently installed the `opentelemetry-collector` using your Helm chart (version 0.34.1).
After installing we've started receiving notifications (called insights) in the GKE cluster console like this:

> This cluster has an admission webhook installed that is intercepting system critical requests in the last 24 hours. Intercepting these requests can impact availability of the GKE Control Plane.

The documentation Google provides points to the `MutatingWebhookConfiguration` and advises you to set up a `namespaceSelector` to omit the `kube-system` and `kube-node-lease` namespaces as well as restricting the rule scope to the filtered resources.
Using the Helm chart, I can set the `namespaceSelector` easily in the chart values file and it works fine but I can't set the rule scope using the Helm chart and since the default value for `scope` is `'*'`, I am forced to edit the rule manually to resolve the notification in the console.

The resources referenced in the admission-webhook templates are `pod`, `instrumentations` and `opentelemetrycollectors`. Since both the `instrumentations` and `opentelemetrycollectors` custom resource definitions are using the `Namespaced` scope and pods are of course also a namespaced resource, I would recommend either just adding a `scope: 'Namespaced'` line to the rules or making `scope` a configurable value.

You can find the relevant documentation reference from Google here: https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks#unsafe-webhooks

### PR DESCRIPTION
**Pull request by b3ndill**
This PR explicitly defines the rule scope for the admission-webhook configurations.
Since the rules are only defining one resource type per rule, I chose to explicitly define the scope instead of providing variables that would allow customization.

This fixes #939 

Thanks in advance!

### CODE REVIEW

**Comment by JaredTan95** [comment]
Not sure this change would impact operator's `Cross namespace instrumentation` feature.

**Comment by b3ndill** [comment]
@povilasv I thought already had, at least running it on my branch doesn't produce any changes.

**Comment by JaredTan95** [comment]
> Not sure this change would impact operator's `Cross namespace instrumentation` feature. Setting `namespaceselector` is enough?

I tested the `cross-namespace instrumentation` in real-world tests, and it workes well.

tested with yaml:
- Instrumentation CR:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: opentelemetry-autoinstrumentation
  namespace: scope-ns-test
spec:
  resource:
    addK8sUIDAttributes: true
  sampler:
    # Enum: always_on, always_off, traceidratio, parentbased_always_on, parentbased_always_off, parentbased_traceidratio, jaeger_remote, xray
    type: always_on
```

- demo app :
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-with-aotu-instrumentation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-deployment-with-aotu-instrumentation-kuberntes
  replicas: 1
  template:
    metadata:
      labels:
        #app: my-deployment-with-aotu-instrumentation-app
        app.kubernetes.io/name: my-deployment-with-aotu-instrumentation-kuberntes
      annotations:
        #sidecar.opentelemetry.io/inject: "false"
        ##instrumentation.opentelemetry.io/inject-sdk: "default/insight-opentelemetry-autoinstrumentation"
        instrumentation.opentelemetry.io/inject-java: "scope-ns-test/opentelemetry-autoinstrumentation"

    spec:
      serviceAccountName: instrumentation-app
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: myapp
        image: ghcr.m.daocloud.io/open-telemetry/opentelemetry-java-instrumentation/smoke-test-spring-boot:jdk11-20211213.1570880324
        #image: docker.m.daocloud.io/library/nginx:1.23.3
        ports:
          - name: http
            containerPort: 8080
```

and java auto-instrumentation injected in init-container. 

So, LGTM

**Review by JaredTan95 — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@b3ndill I merged another operator PR first, so now we need to bump the patch number again and regenerate the examples.   Once you do that I'll make sure this is merged next.

**Comment by b3ndill** [comment]
@TylerHelmuth Done, thanks for letting me know.

**Review by Allex1 — APPROVED** [review]

**Pull request merged**
